[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'rking/ag.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
